### PR TITLE
Issue 175

### PR DESCRIPTION
**Pull request by bkpratt84**
This PR adds anchor links to provide quick links to the examples.

Test URL: [https://vuetify-docs-qhlciarhtf.now.sh/](https://vuetify-docs-qhlciarhtf.now.sh/)

Test Anchor URL: [https://vuetify-docs-qhlciarhtf.now.sh/components/navigation-drawers#temporary](https://vuetify-docs-qhlciarhtf.now.sh/components/navigation-drawers#temporary)

### CODE REVIEW

**Comment by johnleider** [comment]
This is awesome. Is it possible to do this without a dependency (vue-clipboard)? If not let me know and I'll write something up.

**Comment by bkpratt84** [comment]
When I initially looked at copying to the clipboard, everything I found said it's a pain because of the different browser support. I came across that library and used it for simplicity. I am definitely not a clipboard pro so if you can whip something up, that would be awesome!

**Comment by johnleider** [comment]
Valid point, x-browser is important and takes time to test, sounds good.

**Comment by bkpratt84** [comment]
Well, I was on the QuickStart page and saw that it has a copy method that uses document.execCommand('copy'). Could update the url copy function to use the same code. Must have okay browser support or no one has complained yet.

**Comment by KaelWD** [comment]
I've done a simpler implementation of this that doesn't copy to clipboard: #299

**Comment by johnleider** [comment]
Thank you for your contribution, I'm deciding to merge kaels branch due to no dependency.

**Pull request closed without merging**
