### PR TITLE
updated transition name 'fade' to component name

### PR DESCRIPTION
**Pull request by shakee93**
v-fade-transition

### CODE REVIEW

**Comment by johnleider** [comment]
Same with this, re-submit to dev branch and I'll approve, thank you!

**Comment by shakee93** [comment]
there is a blackout issue yes it is the same. but when we use 'fade' as transition it throws an error. there is no component named fade.

**Comment by nekosaur** [comment]
the transition is named `fade-transition`

**Comment by shakee93** [comment]
still the same error component not found `<fade-transition>`

**Comment by nekosaur** [comment]
Are you using dev docs? There was recently a change in CarouselItem (https://github.com/vuetifyjs/vuetify/commit/ce170c3bec49dc338e336242f0b2dcecd45a98ca) so that it uses the css transition, instead of the transition component.

**Comment by shakee93** [comment]
Oh never knew i am not using the dev version.

**Pull request closed without merging**
